name: Integration Tests

on:
  pull_request:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g

jobs:
  it-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache on push
      if: github.event_name == 'push'
      uses: actions/cache@v2
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-eap-it-${{ github.sha }}
        # Restore build outputs from the previous commit (if successful), if current commit hasn't run successfully yet
        restore-keys: |
          ${{ runner.os }}-eap-it-${{ github.event.before }}
    - name: Cache on pull_request
      if: github.event_name == 'pull_request'
      uses: actions/cache@v2
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-eap-it-${{ github.event.pull_request.head.sha }}
        restore-keys: |
          ${{ runner.os }}-eap-it-${{ github.event.before }}
    - name: Integration Tests
      run: ./gradlew --build-cache integrationTest
