name: Update Metadata

on:
  repository_dispatch:
    types: UpdateMetadata

jobs:
  update_metadata:
    name: Update Metadata ${{ github.event.client_payload.uuid }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: write metadata
        run: |
          mkdir -p ${{ github.event.client_payload.path }}
          echo '${{ toJson(github.event.client_payload.metadata) }}' > ${{ github.event.client_payload.path }}/${{ github.event.client_payload.file }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.5.2
        with:
          delete-branch: true
          labels: metadata-update
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.13.0
