name: Update Metadata

on:
  repository_dispatch:
    types: UpdateMetadata

jobs:
  update_metadata:
    name: Update Metadata ${{ github.event.client_payload.uuid }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: write metadata
        run: |
          mkdir -p ${{ github.event.client_payload.path }}
          echo '${{ toJson(github.event.client_payload.metadata) }}' > ${{ github.event.client_payload.path }}/${{ github.event.client_payload.file }}
      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v3.5.2
        with:
          branch: metadata-updates
          delete-branch: true
      - name: Await Check Suites
        uses: jitterbit/await-check-suites@v1
        with:
          ref: refs/heads/metadata-updates
      - name: pull-request merge
        uses: sudo-bot/action-pull-request-merge@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.create-pull-request.outputs.pull-request-number }}
          merge-method: squash
